### ISSUE TITLE
Force GetCert2 to process

### ISSUE THREAD

**Issue by IDriveFaster** [GeorgeSchiro/GetCert2#14]
I created a certificate, but forgot to add the additional SAN names. I added the SAN names but when I go to get the new cert I get the following:

2021-04-09 02:15:10:887 PM  Get certificate process started ...
2021-04-09 02:15:11:137 PM  Nothing to do until 5/8/2021 9:19:01 AM. The current "CN=mail.xxxx.com" certificate doesn't expire until 6/7/2021 9:19:01 AM.

Is there a way to force a renewal with Let's encrypt using GetCert2?

**Comment by GeorgeSchiro** [comment]
That's a great question! Sadly, there is no way to do it by design.

Happily you can do anyway!

Do you read code? Look for "private bool bCertificateNotExpiring" in here: [DoGetCert.cs](https://github.com/GeorgeSchiro/GetCert2/blob/master/GetCertClient/DoGetCert.cs)

The giveaway is the "-DoStagingTests" references. The the code tells you staging certificates are not checked for expiration:

    "Only check valid production certificates for expiration."

So try this:

1. Run "GetCert2.exe" manually (ie. not in auto mode).
2. Click "Setup".
3. Place a check next to "Do staging tests?"
4. Click "GO".

That gets you new (invalid) certificate.

Finally, remove the staging switch and run it again.

Voila!

**Comment by IDriveFaster** [comment]
Thanks George! Worked perfectly.
